// Code generated by "stringer -type statement -linecomment"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_Stmt-0]
	_ = x[_Delete-1]
	_ = x[_Insert-2]
	_ = x[_Select-3]
	_ = x[_Update-4]
}

const _statement_name = "DELETEINSERTSELECTUPDATE"

var _statement_index = [...]uint8{0, 0, 6, 12, 18, 24}

func (i statement) String() string {
	if i >= statement(len(_statement_index)-1) {
		return "statement(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _statement_name[_statement_index[i]:_statement_index[i+1]]
}
